update gituhb action

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -10,15 +10,27 @@ jobs:
   build:
     runs-on: ubuntu-latest
 
-    env:  # Definir variables aquí
-      IMAGE: openfhe-sdk-python
-      OPENFHE_TAG: v1.2.1
-      OPENFHE_SDK_PYTHON_TAG: v0.8.9
-
     steps:
       # Step 1: Checkout the repository
       - name: Checkout repository
         uses: actions/checkout@v3
+
+      # Load environment variables from .env
+      - name: Load environment variables
+        id: load-env
+        run: |
+          if [ ! -f .env ]; then
+            echo ".env file not found, aborting!"
+            exit 1
+          fi
+          # Cargar variables desde .env
+          set -o allexport
+          source .env
+          set +o allexport
+          # Exportar las variables para que estén disponibles en otros pasos
+          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
+          echo "OPENFHE_TAG=$OPENFHE_TAG" >> $GITHUB_ENV
+          echo "OPENFHE_SDK_PYTHON_TAG=$OPENFHE_SDK_PYTHON_TAG" >> $GITHUB_ENV
 
       # Log in to GHCR (GitHub Container Registry)
       - name: Log in to GHCR
